apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-svc
  namespace: todo-namespace
spec:
  clusterIP: None
  ports:
  - name: db
    port: 5432
  selector:
    app: postgresapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: todo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresapp
  serviceName: postgres-svc
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: postgresapp
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: postgres-db
              name: postgres-config
        image: postgres:14.3
        name: postgres
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Mi
---
